services:
  - type: web
    name: bomba-performance-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SENHA_ACESSO
        sync: false
      - key: DATABASE_URL
        sync: false
